version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: prod
    environment:
      - REDIS_URL=redis://redis:6379
      - SMTP_URL=smtp://mailcatcher:1025
    env_file:
      - ../.env
    ports:
      - '3000'
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - '1025'
      - '1080'
  redis:
    image: redis
    ports:
      - '6379'
